server:
  port: 8004

spring:
  application:
    name: COMMON-REDIS
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 100