spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.38.131:3306/yunke?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: root
    password: root
  redis:
    host: 124.223.38.131
    port: 6379
    password: root

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.titos.shareplatform

# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

#YK:
#  sys-conf:
#    enable-mail-register: true
#    front-end-url: 127.0.0.1:8080
#    mail-sender: titos_yunke@qq.com
#  token:
#    secretKey: YUNKE