server:
  port: 8003

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  application:
    name: RPC
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
