server:
  port: 8003

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  application:
    name: RPC
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.38.131:8848
