spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.38.131:3306/yunke?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: root
    password: root
  redis:
    host: 124.223.38.131
    port: 6379
    password: root
  mail:
    host: smtp.qq.com
    port: 465
    username: titos_yunke@qq.com
    password: xbayvkiinblkdcee
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  application:
    name: web_addmin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.titos.personalmanagement
YK:
  sys-conf:
    enable-mail-register: true
    front-end-url: 127.0.0.1:8080
    mail-sender: titos_yunke@qq.com
  token:
    secretKey: YUNKE
server:
  port: 8001

